name: Saltstack Terraform Provider CI Tests

on:
  - pull_request

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
      - name: Vet
        run: make vet
  
  testacc:
    name: Acceptance Tests
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        saltstack-version:
          - "3005"
          - "3004.2"
          - "3004.1"
          - "3004.1"
          - "3004"
          - "3003.5" 
          - "3003.4"
          - "3003.3"
          - "3003.2"
          - "3003.1"
          - "3003"
          - "3002.9"
          - "3002.8"
          - "3002.7"
          - "3002.6"
          - "3002.5"
          - "3002.4"
          - "3002.3"
          - "3002.2"
          - "3002.1"
          - "3002"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.2.*'
          terraform_wrapper: false
      - name: Acceptance Test
        run: make testacc
        env:
          SALTSTACK_VERSION: ${{ matrix.saltstack-version }}
      
      - name: Shut Down Salt Master
        run: make salt-master-down
