name: Saltstack Terraform Provider CI Tests

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.19'
          cache-dependency-path: go.sum
      - name: Test
        run: make test
      - name: Vet
        run: make vet
  
  testacc:
    name: Acceptance Tests
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        saltstack-version:
          - "3006.0"
          - "3006.1"
          - "3006.10"
          - "3006.11"
          - "3006.12"
          - "3006.13"
          - "3006.14"
          - "3006.15"
          - "3006.16"
          - "3006.17"
          - "3006.18"
          - "3006.19"
          - "3006.2"
          - "3006.20"
          - "3006.21"
          - "3006.22"
          - "3006.23"
          - "3006.24"
          - "3006.3"
          - "3006.4"
          - "3006.5"
          - "3006.6"
          - "3006.7"
          - "3006.8"
          - "3006.9"
          - "3007.0"
          - "3007.1"
          - "3007.10"
          - "3007.11"
          - "3007.12"
          - "3007.13"
          - "3007.14"
          - "3007.2"
          - "3007.3"
          - "3007.4"
          - "3007.5"
          - "3007.6"
          - "3007.7"
          - "3007.8"
          - "3007.9"
          - "3005"
          - "3004.2"
          - "3004.1"
          - "3004"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.19'
          cache-dependency-path: go.sum
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '1.2.*'
          terraform_wrapper: false
      - name: Acceptance Test
        run: make testacc
        env:
          SALTSTACK_VERSION: ${{ matrix.saltstack-version }}
      
      - name: Shut Down Salt Master
        run: make salt-master-down
